#
# Jekyll 設定ファイル
#
# https://github.com/mojombo/jekyll/wiki/configuration
safe: true
source: .
destination: ./_site
lsi: false
# github flavored markdown
markdown: redcarpet
# syntax highlight
pygments: true
# files which should not be in destination directory
exclude: ['CNAME', 'package.json', 'node_modules', 'Gruntfile.js']
include: 
# custom build config
analytics:
    enabled: true
    account: UA-XXXXX-X
css:
    minified: true
    bootstrap: true
    bootstrap-responsive: true
js:
    minified: true
    modernizr: true
    respond: true
    jquery: true
    bootstrap: true
appcache:
    enabled: false
