# https://github.com/mojombo/jekyll/wiki/configuration
safe: true
source: .
destination: ./_site
lsi: false
# github flavored markdown
markdown: redcarpet
# syntax highlight
pygments: true
# skil files
exclude: ['CNAME', 'package.json', 'node_modules', 'Gruntfile.js']
# custom build config
analytics:
    enabled: true
    account: UA-XXXXX-X
css:
    minified: true
    bootstrap: true
    bootstrap-responsive: true
    modernizr-respond: true
js:
    minified: true
    jquery: true
    bootstrap: true
appcache:
    enabled: false
